### PR TITLE
Adds support for Template Includes

### PR DESCRIPTION
**Pull request by kyuff**

### CODE REVIEW

**Comment by Crevil** [comment]
This looks interestin. I'm a bit unclear as to what the use cases are. Can you ellaborate a bit on that? eg. When is this useful? What can't be done today wothout this?

**Comment by kyuff** [comment]
> This looks interestin. I'm a bit unclear as to what the use cases are. Can you ellaborate a bit on that? eg. When is this useful? What can't be done today wothout this?

One use-case is to add support for code reuse in the plans.

An example would be from the Go service plan we have in Lunar.

In it, [deployments.tmpl](https://github.com/lunarway/lw-shuttle-go-plan/blob/1c6c7658a567de45dbd8222cd351db213353c971/templates/deployment.tmpl#L135) lists all environment variables available to the service. That's over 150 lines of template code.

Now, if you wanted to create a template that uses the same environment variables, ie for a crontab functionality. Then you would probably end up copy/pasting the same 150+ lines of template code that needs to be maintained across two files.

Another example is the labels that deployment.tmpl and service.tmpl have. They nearly the same output, but slightly different code creating the labels. A code-reuse could standardize that and help avoid drift.

**Comment by Crevil** [comment]
From my understanding, this is what Helm does as well?

Have you considered helm's `include` function? https://helm.sh/docs/chart_template_guide/named_templates/

It makes it possible to pipe into eg. `indent` which is important to make it reuseable ie. label blocks.

**Comment by kyuff** [comment]
That's a much better approach as it supports indentation. I'll withdraw this one and hopefully get back to trying the include at some point in the future. :)

**Comment by Crevil** [comment]
All right. Thanks for taking the time to do this though.

We have been discussing use of kustomize as well that might be able to do something alike, but I think I'm more fond of the `include` function as we can use that for all our templates instead of just kubernetes manifests.

**Pull request closed without merging**
