### PR TITLE
Add GitHub Action

### PR DESCRIPTION
**Pull request by MadsBogeskov**
This PR adds a simple GitHub Action that allows one to install Shuttle in a GitHub Action workflow. This only supports macOS at the moment.

### CODE REVIEW

**Comment by Crevil** [comment]
Can you ellaborate on how to use this and possibly add some documentation for it?

**Comment by MadsBogeskov** [comment]
@Crevil I wrote about it in the README now. This is pretty common for GitHub Actions support. However I just tried to add Linux support as well, and I am waiting for my builds :)

**Comment by MadsBogeskov** [comment]
It worked (on Mac)

**Review by Crevil — APPROVED** [review]
Awesome 🚀 This is super cool.

**Pull request merged**
